### ISSUE TITLE
Dragging focal point breaks preview thumbnail for large images

### ISSUE THREAD

**Issue by bjarnef** [Offroadcode/Zoom-Area-Cropper#3] opened 2017-05-29 18:03 UTC
As soon I drag focal point for a crop, it seems to break the thumbnail.
It might be because it request the image, before the image has been generated.

![image](https://cloud.githubusercontent.com/assets/2919859/26558368/65ae0264-44a8-11e7-88d7-f88d30881075.png)

It seems to be an image, when using large image sizes, with take more time for ImageProcessor to process, than a smaller image.

In viewmode main you could set a max `width` and/or `height` via querystring:

```
ng-src="{{model.value.media.url + '?width=600&height=600'}}"
```
https://github.com/Offroadcode/Zoom-Area-Cropper/blob/cec0bdcc60c9ce13f73928751add164918251fad/src/ZoomAreaCropper/views/ZoomAreaCropperView.html#L19

and then only request full size image in crop/zoom mode preview.

I think this styling is from image cropper, so it probably doesn't need to request a larger size than 600x600px.

```
.gravity-container .viewport {
    max-width: 600px;
}
```

Test image: https://media.koreus.com/201701/allez-faire-loutre.jpg

**Comment by cssquirrel** [comment] 2017-05-30 16:21
@bjarnef I can't recreate the error you're showing in v1.0.1, even when using the same image you have.

Yes, very large images like your test one do cause performance issues, as the crops won't visually update between saves. But I don't get the broken crops. I think a similar bug existed in v1.0.0, but that was fixed by the v1.0.1 hotfix.

Can you confirm your version number, and if it's v1.0.1 that you're still getting the error?

**Comment by cssquirrel** [comment] 2017-05-30 17:37
I'm going to mark this as fixed in v1.0.1 and close it until I can get a confirmation of an issue with that release.

**Comment by cssquirrel** [comment] 2017-05-30 17:38
Fixed in [v1.0.1](https://github.com/Offroadcode/Zoom-Area-Cropper/releases/tag/v1.0.1).

**Comment by bjarnef** [comment] 2017-05-30 20:42
Hi @cssquirrel 

Yes, it was an issue in the latest version of your package (v1.0.1). With smaller images, the thumbnail preview was not broken, but it did seem to happen with large images.

I have tested with v.1.0.2 as well and in Chrome, Firefox and Edge with same result.

**Comment by cssquirrel** [comment] 2017-05-30 20:48
@bjarnef I haven't been able to reproduce this in v1.0.1 or v1.0.2 in any browser. What version of Umbraco are you installed on?

**Comment by cssquirrel** [comment] 2017-05-30 21:53
Fixed in [v1.0.3](https://github.com/Offroadcode/Zoom-Area-Cropper/releases/tag/v1.0.3) by adding a directive to notify controller when image is loaded before peforming any dimensions-related calculation.

**Comment by bjarnef** [comment] 2017-05-30 22:16
I have installed the package in Umbraco 7.6.1 and SQL CE running via WebMatrix. I have just tested with v.1.0.3

Also ensured to update client dependency version, tested with debug true/false, cleared browser cache.

It also happens when enter "preview crop" mode and dragging the zoom slider.

Hmm, seems a bit strange.

When right-clicking the broken image preview and opening it in a new browser window, it has the following querystring:

```
/media/1058/allez-faire-loutre.jpg?crop=null,null,100,100&width=100&height=100
```

![image](https://cloud.githubusercontent.com/assets/2919859/26607370/78638c00-4596-11e7-9d57-462547e0c551.png)

**Comment by bjarnef** [comment] 2017-05-30 22:50
It seems it might be an issue in `$scope.calcCropFromFocus` function with `crop.x` and `crop.y`

When I add this and drag the focal point:

```
console.log("crop.x", crop.x);
console.log("crop.y", crop.y);

$scope.model.value.crops[$scope.selectedCrop] = crop;
```

Where it sometimes returns this:

![image](https://cloud.githubusercontent.com/assets/2919859/26608063/e9459460-4599-11e7-8a46-3b2f8b0d74f0.png)

A few other attempts I manage to drag to focal point, where it makes a valid request without null,null in crop.

![image](https://cloud.githubusercontent.com/assets/2919859/26608289/1203c7ea-459b-11e7-99e0-bd1fa08a480b.png)

**Comment by cssquirrel** [comment] 2017-05-30 23:09
@bjarnef Hm. Ok, I tested pretty thoroughly on a very slow network with the adorable otter image. The calculations of calcCropFromFocus were acting up because the image wouldn't be loaded when the dimensions of the photo were calculated, which is needed to guide the focus handle for its positioning.

I'd made the adjustment in v1.0.3 to wait until the image is loaded and then perform the calculation, and tested it again on a slow network and the fix worked for me. I'm not sure why you'd still be having issues.

To confirm: When you're testing the new version you're deleting the old version in the /app_plugins/ directory before installing the new version?

I'm asking because when testing with new versions I found that uninstalling the package inside Umbraco's admin didn't delete the directory in /app_plugins/ so I'd end up with multiple directories when installing the new version and it would favor the earlier one.

The problem makes sense in v1.0.2 or earlier, as once I was testing on a high latency network I could see it doing exactly what you described and traced it down to setting the wrong dimensions for the crop focus. But I haven't been able to reproduce it again in v1.0.3. Any crops from prior to v1.0.3 would still have null crop values that might cause a problem. So it's with an entirely new node/crops?

I've tested in Umbraco 7.6.1 w/SQL CE as well.

I'll poke around to see if I'm missing something obvious. At the least I can test for null values and replace with 0,0 to prevent a URL malfunction, but I'd like to rule out any other possibilities.

**Comment by bjarnef** [comment] 2017-05-31 06:30
I was just installing the new version via the package installer in backoffice.

![image](https://cloud.githubusercontent.com/assets/2919859/26618222/df858030-45d9-11e7-9ad4-328038d469ea.png)

I have not noticed multiple directories when installing the new version and `zacimageonload` is included in ZoomAreaCropper.js

I have also tried to remove /App_Data/cache which is ImageProcessor's caching folder.

I have only tested on Homepage node, but have just tested with another image too.
Image: http://static2.businessinsider.com/image/54ea3fafecad04883a4c44c2/there-are-so-many-10-billion-startups-that-theres-a-new-name-for-them-decacorns.jpg

![image](https://cloud.githubusercontent.com/assets/2919859/26618635/526f430a-45db-11e7-9813-efbbc36dd063.png)

**Comment by cssquirrel** [comment] 2017-05-31 17:23
OK, this is fairly difficult for me to reproduce, which is making this interesting.

The fact that you're showing Infinity in some of your shots implies that it's trying to divide by zero at some point in the calculation of calcCropByFocus(). The most likely culprit would be either:

         var percent = {
            x: focus.x / $scope.dimensions.width,
            y: focus.y / $scope.dimensions.height
        };

or:

        var sourceDimensions = {
            width: Math.ceil(crop.width / crop.zoom),
            height: Math.ceil(crop.height / crop.zoom)
        };

Considering that $scope.dimensions can only be assigned after the photo has been fully loaded, it shouldn't happen anymore (double checking there). I suppose somehow the crop zoom could be unassigned or 0, which would do it.

Investigating further.

**Comment by cssquirrel** [comment] 2017-05-31 19:06
@bjarnef I'm nailing down some areas where the math could go wonky to limit odds of a null/NaN/Infinty possibility in the math. But in your example URLs I don't see the nulls appearing inside the URLs themselves.

Is there a badly formed URL in any of these instances? If not, the problem might lie beyond the Zoom Area Cropper and inside the fetching of an URL that is chugging slowly on the image processor for generation?

**Comment by cssquirrel** [comment] 2017-05-31 19:10
I can't reproduce this anymore at this point. There is a delay in the crop previews showing when dragging the focus handle on very large images, but after a suitable delay it properly updates the crop once the imageprocessor "catches up".

I'll keep an eye out for this one. If there's more information about it that comes up, please let me know.

**Comment by bjarnef** [comment] 2017-05-31 22:05
@cssquirrel good news is that I don't see the issue much in v.1.0.4 ... it still happens once in a while, but not as much as before.

Another thing I have noticed is that it is possible to drag the focal point outside the image boundaries.

With the otter image is happens more frequent, because of the image size.

**Comment by PeteDuncanson** [comment] 2017-09-08 12:34
Going to close this issue as it seems to have settled down. If it crops up again we can reopen it.

**Closed as completed by PeteDuncanson** 2017-09-08 12:34 UTC
Labels: help wanted
